# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-19 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_order_ordergoods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='childcidname',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='dealerid',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='isxf',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='marketprice',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pmdesc',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='price',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='productnum',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='specifics',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='storenums',
        ),
    ]
