# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-21 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190321_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='istea',
            field=models.BooleanField(default=0),
        ),
    ]
